### ISSUE TITLE
vscode-trace-extension not working with latest trace-viewer depenencies

### ISSUE THREAD

**Issue by bhufmann** [theia-ide/vscode-trace-extension#35]
With the recent updates in the trace viewer components and its dependencies to use `BigInt` for timestamps, the serialization of messages between the webviews and vscode extension will fail because the standard json serializer doesn't support type `BigInt`. 

It will fail with the following message:
```
TypeError: Do not know how to serialize a BigInt
/usr/share/code/resources/app/out/bootstrap-fork.js:5
stack trace: TypeError: Do not know how to serialize a BigInt
	at JSON.stringify (<anonymous>)
	at y (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:3480)
	at g.postMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:73489)
	at TraceViewerPanel.setExperiment (/home/eedbhu/git/vscode-trace-extension/vscode-trace-extension/lib/trace-viewer-panel/trace-viewer-webview-panel.js:125:29)
	at /home/eedbhu/git/vscode-trace-extension/vscode-trace-extension/lib/trace-explorer/trace-tree.js:123:19
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

For example the` Experiment` or `Trace` classes contain timestamp fields which are `BigInt` and causing serialization problems and the vscode trace extension to fail.

To fix this, each message send between webviews and the vscode trace extension itself need to be updated that `BigInt` values are serialized properly (e.g. using a string) and deserialized to `BigInt` on the receiving side.

This issue needs to be fixed before upgrading to the latest traceviewer components which contain many valuable improvements.

**Comment by bhufmann** [comment]
Using https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/56, the serialization / deserialization of BigInt values can be achieved when sending/receiving signals.

**Comment by bhufmann** [comment]
The extension works now with:
- traceviewer-base: 0.2.0-next.7298b48.0
- traceviewer-react-components: "0.2.0-next.7298b48.0"

Serialization is fixed for experiments and it's not an issue for data provider descriptors. Closing this one and open a ticker for improved and more generic serialization implementation.
